assignment2/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('food.urls')),
    
]

food/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


app_name = 'food'
urlpatterns = [
    path('',views.index, name='index'),
    path('<int:item_id>/',views.detail,name='detail'),
    path('item/',views.item,name='item'),
    path('add',views.create_item,name='create_item'),
    path('update/<int:id>/',views.update_item, name='update_item'),
    path('delete/<int:id>/',views.delete_item, name='delete_item'),

]

food/models.py
from django.db import models

# Create your models here.
class Item(models.Model):

    def __str__(self):
        return self.item_name
    

    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,default="https://p.kindpng.com/picc/s/79-798754_hoteles-y-centros-vacacionales-dish-placeholder-hd-png.png")

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields =['item_name','item_desc','item_price','item_image']

food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
# Create your views here.
def index(request):
    item_list = Item.objects.all()
    context = {
        'item_list':item_list,
    }
    return render(request,'food/index.html',context)

def item(request):
    return HttpResponse('<h1>This is an item view</h1>')

def detail(request,item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item' : item,
    }
    return render(request,'food/detail.html',context)

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render (request,'food/item-form.html',{'form':form})

def update_item(request,id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request,'food/item-form.html',{'form':form, 'item':item})

def delete_item(request,id):
    item = Item.objects.get(id=id)
    
    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    return render(request,'food/item-delete.html',{'item':item})
    

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'food/style.css' %}">

    <title>Document</title>
</head>
<body>
    <nav class="navbar sticky-top navbar-dark bg-dark" style="margin-bottom: 20px; ">
        <a href="{% url 'food:index' %}" class="navbar-brand"><h2>FoodMenu</h2></a>

        <div class="navbar">
            <a  class="nav-item nav-link" href="{% url 'food:create_item' %}">Add Item</a>
        </div>
    </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{item.item_image}}" style="height: 300px;" class="card" alt="">
        </div>
        <div class="col-md-6">
            <h1>{{item.item_name}}</h1>
            <h2>{{item.item_desc}}</h2>
            <h3>{{item.item_price}} TK.</h3>
            <div style="display: inline-block;">
                <a href="{% url 'food:update_item' item.id %}" class="btn btn-info" >Update</a>
                <a href="{% url 'food:delete_item' item.id %}" class="btn btn-danger" >Delete</a>
                 
            </div>
            
        </div>
    </div>
</div>


{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FoodMenu</title>
    </head>
<body>

    {% block body %}
        {% for item in item_list%}
            <div class="row" style="margin-bottom: 20px;">
                <div class="col-md-3 offset-md-2">
                  <img class="card" height="150px" src="{{item.item_image}}" alt="">  
                </div>
                <div class="col-md-4">
                    <h3>{{item.item_name}}</h3>
                    <p>{{item.item_desc}}</p>
                    <h5>BDT {{item.item_price}}</h5>
                </div>
                <div class="col-md-2">
                    <a href="{% url 'food:detail' item.id %}" class="btn btn-secondary">Details</a>
                </div>

            </div>

        {% endfor %}

    
    {% endblock%}

    
</body>
</html>

food/templates/food/item-delete.html
{% extends 'food/base.html' %}
{% block body %}
<form method="POST" class="form-inline" style="padding-left: 40px; ">
    {% csrf_token %}        
            <h2 style="margin-right: 10px;">Confirm delete {{item.item_name}} ?</h2>     
            <button type="submit" class="btn btn-danger">Confirm</button>
</form>
{% endblock %}

food/templates/food/item-form.html
{% extends 'food/base.html' %}

{% block body %}

<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit" style="margin-left: 30px;" class="btn btn-success" >Save</button>
</form>

{% endblock%}